config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
    get '/cookies_info', to: 'some_action#index'  
 end
 scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
 # Your existing routes go here
  resources :posts
  root 'home#index'
 end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @user = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-bs-toggle="collapse" data-bs-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('navbar.brand'), root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t('navbar.posts'), posts_path %></li>
        <li><%= link_to t('navbar.sign_in'), new_user_session_path %></li>
        <% if current_user && current_user.superuser? %>
          <li><%= link_to t('navbar.cookies'), cookies_info_path %></li>
        <%end%>

        <% if user_signed_in? %>
          <li><%= link_to t('navbar.sign_up'), new_user_registration_path %></li>
          <li><%= link_to t('navbar.sign_out'), destroy_user_session_path, method: :delete %></li>
          <li><%= link_to t('navbar.edit_profile'), edit_user_registration_path %></li>
          <li><%= link_to t('navbar.new'), new_post_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_study.html.erb
<h1>اسمي يحيى. طالب علوم حاسوب ومبرمج مواقع.</h1>
<p>Ruby on rails</p>
<p>React js</p>
<p>Node js</p>

app/views/home/index.html.erb
<div class="jumbotron" style="background-image: url('<%= asset_path('black.jpg') %>')" style="background-size: cover;
    background-repeat: no-repeat;">
  <h2 style="color: white"><%= t('jumbotron.hello') %></h2><br> <h2 style="color: white"><%= t('jumbotron.I') %></h2>
  <p style="color: white"><%= t('jumbotron.cs') %></p><br>
  <%= link_to t('buttons.posts'), posts_path, class: "btn btn-primary", style: "margin-left: 10px" %>
  <%= link_to t('buttons.contact'), "https://www.t.me/@Yhy7799.com", class: "btn btn-success", style: "margin-left: 10px" %>

</div>
<br>
<h1 style="text-align:center"><%= t('about_me.title') %></h1>

<div class="jumbotron">
  <p >
  <%= t('about_me.content').html_safe %>
</p><br>
  <p>
    <%= render partial: 'home/study' %><br>
    <img src="<%= asset_path('sunset.jpg') %>" class="img-fluid" alt="Sunset" style="  max-width: 70%; max-height: 70%;">
</p><br>
</div>