config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
    get '/cookies_info', to: 'some_action#index'  
 end
 scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
 # Your existing routes go here
  resources :posts
  root 'home#index'
 end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authorize_user, only: %i[:update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: I18n.t('post.created') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: I18n.t('post.updated') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: I18n.t('post.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title,  class:"form-control" %>
  </div>

  <div  class="field form-group">
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image, class:"form-control" %>
  </div>

  <div  class="field form-group">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

    <div  class="field form-group">
    <%= form.text_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h2 style="text-align: center;">
    <%= post.title %>
  </h2>
  <%= image_tag(post.image, class: "image") %>
  <p>
    <%= post.content %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1><%= t('titles.editing_post') %></h1>
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to t('links.show_post'), @post %> | <%= link_to t('links.back_to_posts'), posts_path %>
</div>

app/views/posts/index.html.erb
  <h1><%= t('posts.title') %></h1>

  <div class="jumbotron" id="posts">
    <% @posts.each do |post| %>
        <h2 style="text-align: center;"><%= post.title %></h2>
      <% if post.image.attached? %>
        <%= link_to(post_path(post)) do %>
          <%= image_tag(post.image, class: "image") %>
        <% end %>
      <% end %>
      
      <p><%= t('posts.at', datetime: post.created_at.strftime('%b %d, %Y')) %></p><hr hfont-weight="bold" >
      
    <% end %>
  </div> 

app/views/posts/new.html.erb
<h1><%= t('titles.new_post') %></h1>

<%= render "form", post: @post %>

<br>

app/views/posts/show.html.erb
<div class="jumbotron">
  <%= render @post %><hr>
</div>

<% if current_user %>
<div>
  <%= link_to t('edit'), edit_post_path(@post), class: "btn btn-primary" %> |
  <br><br>
  <%= button_to t('destroy'), @post, method: :delete, class: "btn btn-danger" %>
</div>
<% end %>